#更新检查
Check-Update: true

#连接设置
go-cqhttp:
  #go-cqhttp的config内设置的WebSocket地址+端口
  WebSocket: "ws://127.0.0.1:8080"
  #go-cqhttp的config内设置的Http地址+端口
  Http: "http://127.0.0.1:5700"
  #websocket的连接密钥
  AuthToken:
    enable: false
    value: "123456"

#模块设置
module:
  #绑定模块
  bind:
    #群聊绑定模块
    groupBind:
      #开启监听的群号
      list:
        - "852244501"
      #玩家在群聊发送的绑定关键词  注意：最后需要输入一个空格
      inputKey: "#绑定账号 "
    #绑定过期的时间 单位为秒
    expirationTime: 30
    #绑定的QQ号需要超过多少等级才能进行绑定
    level: 1
    #绑定后的动作
    actions:
      - 'cmd: say 普通玩家执行'
      - 'op: say op执行'
      - 'console: say 控制台执行'
      - 'kether: subtitle "Hello Kether!" by 10 20 10'
  connect:
    enable: false
    #启动监听的群
    group:
      - "852244501"
    #游戏内发送消息在QQ群显示的格式
    #游戏内发送支持papi变量
    # {player}是发送的玩家名字
    mc-qq:
      keywords:
        #是否开启关键词 (关闭则什么都转发)
        enable: true
        #关键词(整个消息包含即可转发)
        text: "转发:"
      text: "{player} : {message}"
    #QQ群发送消息在游戏内显示的格式
    # {sender_id}是发送QQ号
    # {sender} 是发送QQ的名字
    qq-mc:
      keywords:
        #是否开启关键词 (关闭则什么都转发)
        enable: true
        #关键词(整个消息包含即可转发)
        text: "转发:"
      text: "&7[QQ群&7]&7[&b{sender}&7] : &f{message}"
  consoleTool:
    enable: false
    #检测的前缀
    keywords: "cmd:"
    admin:
      - "2479640157"
  #如果玩家没有绑定则进行限制
  whitelist:
    #是否启动
    enable: false
    #不允许进入
    cancelJoin: true
    #不允许移动
    cancelMove: false
    #不允许讲话
    cancelChat: false
    #不允许发送指令
    cancelCommand: false
    #被禁止操作后发送的消息
    #提供占位符
    # {player} 为玩家名字
    message: "&c{player}你未绑定白名单!"








