#主设置
go-cqhttp:
  #go-cqhttp的config内设置的WebSocket地址+端口
  WebSocket: "ws://127.0.0.1:8080"
  #go-cqhttp的config内设置的Http地址+端口
  Http: "http://127.0.0.1:5700"

#模块设置
module:



  #绑定模块
  bind:
    #群聊绑定模块
    groupBind:
      #开启监听的群号
      list:
        - "852244501"
      #玩家在群聊发送的绑定关键词  注意：最后需要输入一个空格
      inputKey: "#绑定账号 "
    #绑定过期的时间
    expirationTime: 1
    #绑定的QQ号需要超过多少等级才能进行绑定
    level: 1
    #绑定后的动作
    actions:
      - 'cmd: say 普通玩家执行'
      - 'op: say op执行'
      - 'console: say 控制台执行'
      - 'kether: subtitle "Hello Kether!" by 10 20 10'



  #定期清除模块（作用是定期检查游戏内绑定的玩家是否还在群内，否则取消绑定）
  check:
    #开启监听的群号
    list:
      - "852244501"
    #每日的多少点检查一次
    time: "00:00"



  connect:
    #启动监听的群
    group:
      - "852244501"
    #游戏内发送消息在QQ群显示的格式
    #游戏内发送支持papi变量
    mc-qq:
      keywords:
        #是否开启关键词 (关闭则什么都转发)
        enable: true
        #关键词(整个消息包含即可转发)
        #例子：在游戏内发送
        # - 转发:阿巴阿巴阿巴
        # - 阿巴阿巴转发:阿巴
        #都会会转发消息
        text: "转发:"
      text: "%player_name% : {message}"
    #QQ群发送消息在游戏内显示的格式
    # {sender_id}是发送QQ号
    # {sender} 是发送QQ的名字
    qq-mc:
      keywords:
        #是否开启关键词 (关闭则什么都转发)
        enable: true
        text: "转发:"
      text: "&7[QQ群&7]&7[&b{sender}&7] : &f{message}"






